// Generates packages/ui/registry/lib/world-map.ts by downloading Natural Earth
// 110m land polygons and rasterizing point-in-polygon into a 1° grid (360x180 bits = 8,100 bytes).
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const GEOJSON_URL =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson'

function pointInRing(x, y, ring) {
  let inside = false
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0]
    const yi = ring[i][1]
    const xj = ring[j][0]
    const yj = ring[j][1]
    const intersect = yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi
    if (intersect) inside = !inside
  }
  return inside
}

function pointInPolygon(x, y, poly) {
  if (!pointInRing(x, y, poly[0])) return false
  for (let i = 1; i < poly.length; i++) {
    if (pointInRing(x, y, poly[i])) return false
  }
  return true
}

async function main() {
  console.log('Downloading Natural Earth ne_110m_land.geojson...')
  const res = await fetch(GEOJSON_URL)
  if (!res.ok) throw new Error(`Failed to fetch geojson: ${res.statusText}`)
  const geojson = await res.json()

  const polys = []
  for (const f of geojson.features) {
    const g = f.geometry
    const add = (coords) => {
      let minX = Infinity
      let maxX = -Infinity
      let minY = Infinity
      let maxY = -Infinity
      for (const [x, y] of coords[0]) {
        if (x < minX) minX = x
        if (x > maxX) maxX = x
        if (y < minY) minY = y
        if (y > maxY) maxY = y
      }
      polys.push({ coords, minX, maxX, minY, maxY })
    }
    if (g.type === 'Polygon') add(g.coordinates)
    else if (g.type === 'MultiPolygon') g.coordinates.forEach(add)
  }

  function isLandPoly(lng, lat) {
    for (const p of polys) {
      if (lng >= p.minX && lng <= p.maxX && lat >= p.minY && lat <= p.maxY) {
        if (pointInPolygon(lng, lat, p.coords)) return true
      }
    }
    return false
  }

  const width = 360
  const height = 180
  const buffer = Buffer.alloc((width * height) / 8)

  let landCount = 0
  for (let r = 0; r < height; r++) {
    const lat = 90 - (r + 0.5)
    for (let c = 0; c < width; c++) {
      const lng = -180 + (c + 0.5)
      if (isLandPoly(lng, lat)) {
        const bit = r * width + c
        buffer[bit >> 3] |= 1 << (7 - (bit & 7))
        landCount++
      }
    }
  }

  const base64 = buffer.toString('base64')
  console.log(`Rasterized ${landCount} land cells. Base64 length: ${base64.length}`)

  const code = `/**
 * Compact rasterized 1-degree land bitset (360x180 bits = 8,100 bytes).
 * Source: Natural Earth ne_110m_land.geojson (public domain, Natural Earth / nvkelso/natural-earth-vector).
 * Generated by packages/ui/scripts/gen-world.mjs.
 */

// prettier-ignore
const LAND_DATA =
  '${base64}'

function decodeBits(b64: string): Uint8Array {
  if (typeof atob === 'function') {
    const bin = atob(b64)
    const bytes = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; i++) {
      bytes[i] = bin.charCodeAt(i)
    }
    return bytes
  }
  return new Uint8Array(Buffer.from(b64, 'base64'))
}

const landBitset: Uint8Array = decodeBits(LAND_DATA)

/**
 * Returns true if the given latitude [-90, 90] and longitude [-180, 180] is on land.
 */
export function isLand(lat: number, lng: number): boolean {
  if (lat < -90 || lat > 90 || Number.isNaN(lat) || Number.isNaN(lng)) return false
  const row = Math.min(179, Math.max(0, Math.floor(90 - lat)))
  const normalizedLng = (((lng + 180) % 360) + 360) % 360
  const col = Math.min(359, Math.max(0, Math.floor(normalizedLng)))
  const bitIndex = row * 360 + col
  const byte = landBitset[bitIndex >> 3]
  return ((byte >> (7 - (bitIndex & 7))) & 1) === 1
}

export interface LandPointsOptions {
  /** Minimum latitude to include. Default -60 (excludes Antarctica by default for denser view). */
  minLat?: number
  /** Maximum latitude to include. Default 84. */
  maxLat?: number
}

/**
 * Generates an array of [lat, lng] coordinates covering land masses at the given step size.
 */
export function landPoints(
  step = 1,
  { minLat = -60, maxLat = 84 }: LandPointsOptions = {},
): [number, number][] {
  const points: [number, number][] = []
  const safeStep = Math.max(0.5, step)

  for (let lat = maxLat; lat >= minLat; lat -= safeStep) {
    for (let lng = -180; lng <= 180; lng += safeStep) {
      if (isLand(lat, lng)) {
        points.push([Math.round(lat * 100) / 100, Math.round(lng * 100) / 100])
      }
    }
  }

  return points
}
`

  const target = join(
    dirname(fileURLToPath(import.meta.url)),
    '..',
    'registry',
    'lib',
    'world-map.ts',
  )
  writeFileSync(target, code, 'utf8')
  console.log(`Wrote ${target}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
